name: GhostBuster
main: io.github.rypofalem.ghostbuster.GhostBusterPlugin
version: 1.0
website: https://github.com/RypoFalem
author: RypoFalem
description: Prevents a common cause of "ghost blocks"
commands:
